### ISSUE TITLE
Linux Archive Type

### ISSUE THREAD

**Issue by d10sfan** [popcar2/CleanDoom#3]
Im attempting to add this to luxtorpeda, which includes a zip unarchiver in the client. It's saying that the type is unsupported, when most zips work fine.

What's the file format here, and is it possible to upload it as a tar.gz or tar.xz instead?

Thanks!

**Comment by popcar2** [comment]
That'd odd, it's a zip archive with LZMA compression which I thought was supported everywhere. I can use a more supported compression type but that'll make the file like 25% bigger.

Here's the newest build as a tar.xz, give it a try and let me know: https://send.vis.ee/download/e51e197738b9e418/#KTi3w3oUg5rzYyEvnOkM0w

**Comment by d10sfan** [comment]
It looks like the tar.xz should work

**Comment by d10sfan** [comment]
Could you upload that to the GitHub release if you don't mind? Thanks!

**Comment by popcar2** [comment]
> Could you upload that to the GitHub release if you don't mind? Thanks!

Sure, the newest release has it now.

**Comment by d10sfan** [comment]
Thanks! That looks like it did the trick
