### ISSUE TITLE
Some PK3 files not openable

### ISSUE THREAD

**Issue by clayote** [popcar2/CleanDoom#5]
I'm running CleanDoom 1.0.3 on Linux Mint 21.3 with gzdoom g4.11.3.

I am trying to play the PK3s from [this pack](https://www.mediafire.com/file/9wdck062y62gcei/PSXDoom_2.135.zip/file).

(I'm aware this project was abandoned. Further attempts at porting PlayStation Doom have all involved modifying GZDoom, they don't seem to have repackaged it, they won't compile right for me, and I can't really be bothered to contribute.)

GZDoom can open those PK3s just fine, as `gzdoom PSXDOOM/PSXDOOM.PK3 PSXDOOM/PSXTCMUS.PK3` results in a reasonable approximation of the PlayStation title screen.

CleanDoom, however, won't show those PK3s in its file browser.

**Comment by popcar2** [comment]
Thanks for the report, I'll fix this in the next update. For now, can you try renaming `.PK3` to `.pk3`? Cleandoom had a bug regarding uppercase file extensions.

**Comment by popcar2** [comment]
Should be fixed in the latest update!
